firma/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.views.generic import ListView
from .models import Firm

from .views import (index, FirmListView)

from django.urls import path
from . import views


app_name = "firma"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:firm_name>/results/', views.results, name='results'),
    path('allfirm/', FirmListView.as_view(), name='allfirm'),

]


# from django.urls import path
# from . import views
#
# app_name = "firma"
# urlpatterns = [
#     path('', views.IndexView.as_view(), name='index'),
# ]

mojprojekt/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
     path('firma/', include('firma.urls')),
     path('admin/', admin.site.urls),
 ]

firma/models.py
import datetime
from django.db import models
from django.utils import timezone


class Firm(models.Model):
    firm_name = models.CharField(max_length=300)
    detail = models.TextField()
    add_date = models.DateTimeField()
    searching_date = models.DateTimeField(blank=True, null=True )  # do przyszłego wyświetlania ostatnich wyszukiwanych firm

    def __str__(self):
        return self.firm_name

    def was_searching_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.searching_date <= now
    was_searching_recently.admin_order_field = 'searching_date'
    was_searching_recently.boolean = True
    was_searching_recently.short_description = 'Searching recently?'

firma/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from django.shortcuts import render
from django.db.models import Q
from .models import Firm


def index(request):      # do dodania wyświetlanie ostatnio wyszukiwanych firm

    if request.method == 'GET':
        query = request.GET.get('q')

        submitbutton= request.GET.get('submit')

        if query is not None:
            lookups = Q(firm_name__icontains=query) | Q(add_date__icontains=query)

            results = Firm.objects.filter(lookups).distinct()

            context = {'results': results,
                     'submitbutton': submitbutton}

            return render(request, 'firma/results.html', context)

        else:
            return render(request, 'firma/index.html')

    else:
        return render(request, 'firma/index.html')


def results(request, firm_name):
    firm = get_object_or_404(Firm, pk=firm_name)
    return render(request, 'firma/results.html', {'firm': firm})


class FirmListView(generic.ListView):
    all_firms = Firm.objects.order_by('-add_date')
    template_name = 'firma/allfirm.html'
    context_object_name = 'all_firms'

    def get_queryset(self):
        """Return the last five published questions."""
        return Firm.objects.order_by('-add_date')


# class IndexView(generic.ListView):
#     template_name = 'firma/index.html'   #używamy template_name, aby powiedzieć ListView, by używała naszego istniejącego szablonu "firma/index.html".
#     context_object_name = 'latest_searching_list'  # dla ListView automatycznie generowaną zmienną kontekstową jest question_list. Aby to nadpisać nadajemy wartość atrybutowi context_object_name, wskazując, że chcemy użyć zamiast niej latest_question_list
#
#def get_queryset(self):
#         """Return the last five searching firms. """
#         return Firm.objects.filter(
#             searching_date__lte=timezone.now()
#         ).order_by('searching_date')[:5]

firma/templates/firma/allfirm.html
{% load static %}

<head>
    <h3>FIRMY, KTÓRE NIE TESTUJĄ SWOICH PRODUKTÓW NA ZWIERZĘTACH</h3>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'firma/style.css' %}" />
</head>
<body class="allfirm">
<div class="allfirm">
{% if all_firms %}
    <ul>
    {% for firm in all_firms %}
        <li><a href="{{ firm.detail}}">{{ firm.firm_name }}</a></li>
    {% endfor %}
    </ul>
</div>
{% else %}
    <p>No firms are available.</p>
{% endif %}
<form action="{% url 'firma:index' %}" >
<input type="submit" name="submit" value="Cofnij"/>
</form>
</body>

firma/templates/firma/index.html
{% load static %}

<head>
    <h1>CZY TWOJA ULUBIONA FIRMA TESTUJE PRODUKTY NA ZWIERZĘTACH?</h1>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'firma/style.css' %}" />
</head>
<body>
<br/>
<i> Wpisz w okno wyszukiwarki nazwę swojej ulubionej firmy i sprawdź czy znajduje się w naszej bazie firm,
<br/>
    które NIE TESTUJĄ swoich produktów na zwierzętach.</i>
<br/>
<br/>
<form action="{% url 'firma:index' %}" method="GET" value="{{request.GET.q}}">
Search <input type="text" name="q" value="{{request.GET.q}}" placeholder="Wpisz nazwę firmy"/>
<input type="submit" name="submit" value="Szukaj"/>
</form>
<a href="https://www.mediapeta.com/peta/PDF/companiesdotest.pdf">Pełny spis firm, zweryfikowanych przez PETA, znajdziesz tutaj.</a>
<br/>
<a href="{% url 'firma:allfirm' %}">A tu znajdziesz wszystkie firmy z naszej bazy.</a>
<div>
<a href="https://www.freepik.com/free-photos-vectors/flower">Flower photo created by jcomp - www.freepik.com</a>
</div>
</body>

firma/templates/firma/results.html
{% load static %}

{% if submitbutton == 'Szukaj' and request.GET.q != '' %}
{% if results %}

<h1>
        Firma <b>{{ request.GET.q }}</b> jest w naszej bazie!
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'firma/style.css' %}" />
</h1>
<br/>
Oznacza to, że firma ta nie testuje swoich produktów na zwierzętach.
<br/>
<br/>
{% for result in results %}
<br/>
<h2> Chcesz wiedzieć więcej o firmie {{result.firm_name}} ? </h2>

<a href="{{result.detail}}">zajrzyj na ich stronę!</a>
<br/>
<br/>
{% endfor %}
{% else %}
<h1>
        <b>Niestety! Tej firmy nie ma w naszej bazie.</b>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'firma/style.css' %}" />
</h1>
<br/>
Oznacza to, że testuje swoje produkty na zwierzętach, lub brak jest informacji
o tym aspekcie jej działań.
<br/> A może jeszcze nie mamy jej w swojej bazie?
<br/>
<br/>
Jeśli chcesz coś dodać, daj nam znać!
<br/>
<br/>
{% endif %}
{% endif %}
<form action="{% url 'firma:index' %}" >
<input type="submit" name="submit" value="Cofnij"/>
</form>